{% set name = "fastcan" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastcan-{{ version }}.tar.gz
  sha256: a4d3b285671920ed413462a4a3536794f494cd4373501a68f6820e1ecb151fbe

build:
  number: 0
  skip: true  # [py<310]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - meson-python                          # [build_platform != target_platform]
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - meson-python
    - cython
    - scikit-learn >=1.7.0
    - python-build
    - pip
    # See https://github.com/conda-forge/openmp-feedstock/issues/126
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - scikit-learn >=1.7.0

test:
  imports:
    - fastcan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastcan.readthedocs.io/en/latest/
  summary: A fast canonical-correlation-based feature selection method
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/scikit-learn-contrib/fastcan/

extra:
  recipe-maintainers:
    - MatthewSZhang
