{% set name = "fastcan" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f096487acc9898c4a9af4906bffeb9fd2203a277a3e94c0fc586097cc0e769dd

build:
  number: 1
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - meson-python                          # [build_platform != target_platform]
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - meson-python
    - cython
    - scikit-learn >=1.6.0
    - python-build
    - pip
    # See https://github.com/conda-forge/openmp-feedstock/issues/126
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - scikit-learn >=1.6.0

test:
  imports:
    - fastcan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastcan.readthedocs.io/en/latest/
  summary: A fast canonical-correlation-based search algorithm
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/scikit-learn-contrib/fastcan/

extra:
  recipe-maintainers:
    - MatthewSZhang
